[[questions]]
question = "The global coefficient is based on the ration between the number of triangles divided by the total number of triplets (open + close). True or False."
answer = "True!"

[[questions]]
question = "What is an Euler circuits?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."
